// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: accounts.sql

package db

import (
	"context"
)

const getAccountBalance = `-- name: GetAccountBalance :one
SELECT COALESCE(SUM(CASE WHEN side = 'credit' THEN amount ELSE -amount END), 0)::bigint AS balance
FROM ledger_postings
WHERE account_id = $1
`

func (q *Queries) GetAccountBalance(ctx context.Context, accountID string) (int64, error) {
	row := q.db.QueryRow(ctx, getAccountBalance, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}

const lockAccount = `-- name: LockAccount :one
SELECT id, owner, is_active, created_at
FROM accounts
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockAccount(ctx context.Context, id string) (Account, error) {
	row := q.db.QueryRow(ctx, lockAccount, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}
