// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: idempotency.sql

package db

import (
	"context"
)

const lockIdempotencyByKey = `-- name: LockIdempotencyByKey :one
SELECT key, fingerprint, status, result_ref, created_at, updated_at
FROM idempotency_keys
WHERE key = $1
FOR UPDATE
`

func (q *Queries) LockIdempotencyByKey(ctx context.Context, key string) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, lockIdempotencyByKey, key)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Fingerprint,
		&i.Status,
		&i.ResultRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markIdempotencyInProgress = `-- name: MarkIdempotencyInProgress :one
UPDATE idempotency_keys
SET status = $3, updated_at = now()
WHERE key = $1 AND fingerprint = $2 AND status = $4
RETURNING key, fingerprint, status, result_ref, created_at, updated_at
`

type MarkIdempotencyInProgressParams struct {
	Key         string `json:"key"`
	Fingerprint string `json:"fingerprint"`
	Status      string `json:"status"`
	Status_2    string `json:"status_2"`
}

func (q *Queries) MarkIdempotencyInProgress(ctx context.Context, arg MarkIdempotencyInProgressParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, markIdempotencyInProgress,
		arg.Key,
		arg.Fingerprint,
		arg.Status,
		arg.Status_2,
	)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Fingerprint,
		&i.Status,
		&i.ResultRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveIdempotency = `-- name: ReserveIdempotency :one
INSERT INTO idempotency_keys (key, fingerprint, status, created_at, updated_at)
VALUES ($1, $2, $3, now(), now())
ON CONFLICT (key) DO NOTHING
RETURNING key, fingerprint, status, result_ref, created_at, updated_at
`

type ReserveIdempotencyParams struct {
	Key         string `json:"key"`
	Fingerprint string `json:"fingerprint"`
	Status      string `json:"status"`
}

func (q *Queries) ReserveIdempotency(ctx context.Context, arg ReserveIdempotencyParams) (IdempotencyKey, error) {
	row := q.db.QueryRow(ctx, reserveIdempotency, arg.Key, arg.Fingerprint, arg.Status)
	var i IdempotencyKey
	err := row.Scan(
		&i.Key,
		&i.Fingerprint,
		&i.Status,
		&i.ResultRef,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveIdempotencyCompleted = `-- name: SaveIdempotencyCompleted :execrows
UPDATE idempotency_keys
SET status = $2, result_ref = $3, updated_at = now()
WHERE key = $1
`

type SaveIdempotencyCompletedParams struct {
	Key       string  `json:"key"`
	Status    string  `json:"status"`
	ResultRef *string `json:"result_ref"`
}

func (q *Queries) SaveIdempotencyCompleted(ctx context.Context, arg SaveIdempotencyCompletedParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveIdempotencyCompleted, arg.Key, arg.Status, arg.ResultRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
