// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: journals.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getJournal = `-- name: GetJournal :one
SELECT id, reference, description, metadata, created_at
FROM ledger_journal
WHERE id = $1
`

func (q *Queries) GetJournal(ctx context.Context, id string) (LedgerJournal, error) {
	row := q.db.QueryRow(ctx, getJournal, id)
	var i LedgerJournal
	err := row.Scan(
		&i.ID,
		&i.Reference,
		&i.Description,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const insertJournal = `-- name: InsertJournal :exec
INSERT INTO ledger_journal (id, reference, description, metadata, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertJournalParams struct {
	ID          string             `json:"id"`
	Reference   string             `json:"reference"`
	Description string             `json:"description"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertJournal(ctx context.Context, arg InsertJournalParams) error {
	_, err := q.db.Exec(ctx, insertJournal,
		arg.ID,
		arg.Reference,
		arg.Description,
		arg.Metadata,
		arg.CreatedAt,
	)
	return err
}

const insertPosting = `-- name: InsertPosting :exec
INSERT INTO ledger_postings (journal_id, posting_index, account_id, amount, side, currency)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPostingParams struct {
	JournalID    string `json:"journal_id"`
	PostingIndex int32  `json:"posting_index"`
	AccountID    string `json:"account_id"`
	Amount       int64  `json:"amount"`
	Side         string `json:"side"`
	Currency     string `json:"currency"`
}

func (q *Queries) InsertPosting(ctx context.Context, arg InsertPostingParams) error {
	_, err := q.db.Exec(ctx, insertPosting,
		arg.JournalID,
		arg.PostingIndex,
		arg.AccountID,
		arg.Amount,
		arg.Side,
		arg.Currency,
	)
	return err
}

const listJournalPostings = `-- name: ListJournalPostings :many
SELECT account_id, amount, side, currency
FROM ledger_postings
WHERE journal_id = $1
ORDER BY posting_index ASC
`

type ListJournalPostingsRow struct {
	AccountID string `json:"account_id"`
	Amount    int64  `json:"amount"`
	Side      string `json:"side"`
	Currency  string `json:"currency"`
}

func (q *Queries) ListJournalPostings(ctx context.Context, journalID string) ([]ListJournalPostingsRow, error) {
	rows, err := q.db.Query(ctx, listJournalPostings, journalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJournalPostingsRow{}
	for rows.Next() {
		var i ListJournalPostingsRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Amount,
			&i.Side,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
