// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        string             `json:"id"`
	Owner     string             `json:"owner"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdempotencyKey struct {
	Key         string             `json:"key"`
	Fingerprint string             `json:"fingerprint"`
	Status      string             `json:"status"`
	ResultRef   *string            `json:"result_ref"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type LedgerJournal struct {
	ID          string             `json:"id"`
	Reference   string             `json:"reference"`
	Description string             `json:"description"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LedgerPosting struct {
	ID           int64  `json:"id"`
	JournalID    string `json:"journal_id"`
	PostingIndex int32  `json:"posting_index"`
	AccountID    string `json:"account_id"`
	Amount       int64  `json:"amount"`
	Side         string `json:"side"`
	Currency     string `json:"currency"`
}

type OutboxEvent struct {
	ID          int64              `json:"id"`
	Type        string             `json:"type"`
	AggregateID string             `json:"aggregate_id"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	PublishedAt pgtype.Timestamptz `json:"published_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
