// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (type, aggregate_id, payload, occurred_at)
VALUES ($1, $2, $3, $4)
`

type InsertOutboxEventParams struct {
	Type        string             `json:"type"`
	AggregateID string             `json:"aggregate_id"`
	Payload     []byte             `json:"payload"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.Type,
		arg.AggregateID,
		arg.Payload,
		arg.OccurredAt,
	)
	return err
}
