// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	GetAccountBalance(ctx context.Context, accountID string) (int64, error)
	GetJournal(ctx context.Context, id string) (LedgerJournal, error)
	InsertJournal(ctx context.Context, arg InsertJournalParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	InsertPosting(ctx context.Context, arg InsertPostingParams) error
	ListJournalPostings(ctx context.Context, journalID string) ([]ListJournalPostingsRow, error)
	LockAccount(ctx context.Context, id string) (Account, error)
	LockIdempotencyByKey(ctx context.Context, key string) (IdempotencyKey, error)
	MarkIdempotencyInProgress(ctx context.Context, arg MarkIdempotencyInProgressParams) (IdempotencyKey, error)
	ReserveIdempotency(ctx context.Context, arg ReserveIdempotencyParams) (IdempotencyKey, error)
	SaveIdempotencyCompleted(ctx context.Context, arg SaveIdempotencyCompletedParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
